from tkinter import *
from tkinter import messagebox
import enchant
dict = enchant.Dict("en_US")
global myletters
myletters = {}
NO_OF_LETTER_LIST=[3,4,5,6,7,8,9,10,11,12,13,14,15]
Alphabet_List=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
IMPORTANCE_LIST=[1,2,3,4,5,6,7,8,9]
global letter_scores
global word_score
global total_score
letter_score = 0
word_score = 0
total_score = 0
#--------------------------------------FUNCTIONS---------------------------------------------------
#for letters:
def get_info3():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)           
def get_info4():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info5():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info6():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info7():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info8():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        myletters[letter8.get()]=importance8.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info9():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        myletters[letter8.get()]=importance8.get()
        myletters[letter9.get()]=importance9.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info10():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        myletters[letter8.get()]=importance8.get()
        myletters[letter9.get()]=importance9.get()
        myletters[letter10.get()]=importance10.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info11():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        myletters[letter8.get()]=importance8.get()
        myletters[letter9.get()]=importance9.get()
        myletters[letter10.get()]=importance10.get()
        myletters[letter11.get()]=importance11.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info12():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        myletters[letter8.get()]=importance8.get()
        myletters[letter9.get()]=importance9.get()
        myletters[letter10.get()]=importance10.get()
        myletters[letter11.get()]=importance11.get()
        myletters[letter12.get()]=importance12.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info13():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        myletters[letter8.get()]=importance8.get()
        myletters[letter9.get()]=importance9.get()
        myletters[letter10.get()]=importance10.get()
        myletters[letter11.get()]=importance11.get()
        myletters[letter12.get()]=importance12.get()
        myletters[letter13.get()]=importance13.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info14():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        myletters[letter8.get()]=importance8.get()
        myletters[letter9.get()]=importance9.get()
        myletters[letter10.get()]=importance10.get()
        myletters[letter11.get()]=importance11.get()
        myletters[letter12.get()]=importance12.get()
        myletters[letter13.get()]=importance13.get()
        myletters[letter14.get()]=importance14.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
def get_info15():
        myletters[letter1.get()]=importance1.get()
        myletters[letter2.get()]=importance2.get()
        myletters[letter3.get()]=importance3.get()
        myletters[letter4.get()]=importance4.get()
        myletters[letter5.get()]=importance5.get()
        myletters[letter6.get()]=importance6.get()
        myletters[letter7.get()]=importance7.get()
        myletters[letter8.get()]=importance8.get()
        myletters[letter9.get()]=importance9.get()
        myletters[letter10.get()]=importance10.get()
        myletters[letter11.get()]=importance11.get()
        myletters[letter12.get()]=importance12.get()
        myletters[letter13.get()]=importance13.get()
        myletters[letter14.get()]=importance14.get()
        myletters[letter15.get()]=importance15.get()
        print(myletters)
        Window_2.destroy()
        global Window_3
        Window_3 = Tk()
        Window_3.configure(background="light blue")
        Window_3.title("Word Game")
        Window_3.geometry("800x600")
        Label(Window_3, text="Enter your word using your chosen letters", fg="Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
        Label(Window_3, text="Letters:", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
        Label(Window_3, text=myletters.keys(), fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=1)
        Label(Window_3, text="Word:", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=2, column = 0)
        global myword
        myword = StringVar()
        Entry(Window_3, textvariable=myword).grid(row=2, column=1)
        Button(text="submit", command=check_word).grid(row=3, column=1)
#for no of letters
def get_no_of_letters():
    global no_of_let
    no_of_let=no_of_letters.get()
    Window_1.destroy()
def thankyouscreen():
    global Window_4
    Window_4 = Tk()
    Window_4.configure(background="light blue")
    Window_4.title("Word Game")
    Window_4.geometry("800x600") 
    Label(Window_4, text="Thankyou For Playing!", fg="yellow", bg= "Black", font='timesnewroman 20 bold', relief=RAISED).grid(row=0, column = 2)
    Label(Window_4, text="Your Total Score is:", fg="yellow", bg= "Black", font='timesnewroman 16 bold', relief=RAISED).grid(row=1, column = 1)
    Label(Window_4, text=str(total_score), fg="yellow", bg= "Black", font='timesnewroman 16 bold', relief=RAISED).grid(row=1, column = 2)
    Window_4.mainloop()
def check_word():
    global word
    global letter_score
    global word_score
    global total_score
    letter_score = 0
    word_score = 0
    word = myword.get()
    if (word.isnumeric()):
        messagebox.showerror("Error", "Enter a Word!")
    else:
        if not dict.check(word):
            messagebox.showerror("Error", "The word is not an English word. Try again!")
        else:
            for alphabet in word:
                if alphabet not in myletters.keys():
                    word_score = 0
                    letter_score=0
                    messagebox.showerror("Error", "The word does not contain the allowed letters!")
                    break
                #calculating points for that word
                letter_score = int(myletters[alphabet])
                word_score = word_score + letter_score
            flag1 = True
            for key in myletters:
                if key not in word:
                    flag1 = False
            #increments score by 50 if every letter is utilized
            if flag1 == True:
                word_score = word_score + 50
            #increments the total score
            total_score = total_score + word_score
            
            messagebox.showinfo("Word Score", "Score for this word is:"+str(word_score))
            
            word_score = 0
            letter_score=0
            
            ask_user = messagebox.askyesno("Continue?", "Do you want to continue?")
            if ask_user==False:
                Window_3.destroy()
                thankyouscreen()
#------------------------------------FUNCTIONS END------------------------------------------------------
Window_1 = Tk()
Window_1.configure(background="light blue")
Window_1.title("Word Game")
Window_1.geometry("800x600") 
Label(Window_1, text="Enter no. of letters in your word [range: 3-15]", fg="yellow", bg= "Black",padx =100, pady = 25, font='timesnewroman 16 bold', relief=RAISED).grid(row=0, column = 0)
no_of_letters = IntVar(value=3)
no_of_letters_drop = OptionMenu(Window_1, no_of_letters, *NO_OF_LETTER_LIST)
no_of_letters_drop.grid(row=0, column = 1)
Button(text="Submit", command=get_no_of_letters).grid()
Window_1.mainloop()
global Window_2
Window_2 = Tk()
Window_2.configure(background="light blue")
Window_2.title("Word Game")
Window_2.geometry("800x600")
Label(Window_2, text="Enter letters in your word and the importance of each letter ", fg="Yellow", bg="Black",padx =100, pady = 25, font='timesnewroman 11 bold', relief=RAISED).grid(row=0, column = 0)
Label(Window_2, text="Letters", fg="Yellow", bg="Black",font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column=0)
Label(Window_2, text="Importance[1-9]", fg= "Yellow", bg="Black", font='timesnewroman 11 bold', relief=RAISED).grid(row=1, column = 1)
#no of options based on 
if (no_of_let==3):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    Button(text="submit", command=get_info3).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==4):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    Button(text="submit", command=get_info4).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==5):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    Button(text="submit", command=get_info5).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==6):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    Button(text="submit", command=get_info6).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==7):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    Button(text="submit", command=get_info7).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==8):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    letter8 = StringVar(value="Choose a Letter")
    importance8= IntVar(value=1)
    OptionMenu(Window_2, letter8, *Alphabet_List).grid(row=9, column=0)
    OptionMenu(Window_2, importance8, *IMPORTANCE_LIST).grid(row=9, column=1)
    Button(text="submit", command=get_info8).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==9):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    letter8 = StringVar(value="Choose a Letter")
    importance8= IntVar(value=1)
    OptionMenu(Window_2, letter8, *Alphabet_List).grid(row=9, column=0)
    OptionMenu(Window_2, importance8, *IMPORTANCE_LIST).grid(row=9, column=1)
    letter9 = StringVar(value="Choose a Letter")
    importance9= IntVar(value=1)
    OptionMenu(Window_2, letter9, *Alphabet_List).grid(row=10, column=0)
    OptionMenu(Window_2, importance9, *IMPORTANCE_LIST).grid(row=10, column=1)
    Button(text="submit", command=get_info9).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==10):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    letter8 = StringVar(value="Choose a Letter")
    importance8= IntVar(value=1)
    OptionMenu(Window_2, letter8, *Alphabet_List).grid(row=9, column=0)
    OptionMenu(Window_2, importance8, *IMPORTANCE_LIST).grid(row=9, column=1)
    letter9 = StringVar(value="Choose a Letter")
    importance9= IntVar(value=1)
    OptionMenu(Window_2, letter9, *Alphabet_List).grid(row=10, column=0)
    OptionMenu(Window_2, importance9, *IMPORTANCE_LIST).grid(row=10, column=1)
    letter10 = StringVar(value="Choose a Letter")
    importance10= IntVar(value=1)
    OptionMenu(Window_2, letter10, *Alphabet_List).grid(row=11, column=0)
    OptionMenu(Window_2, importance10, *IMPORTANCE_LIST).grid(row=11, column=1)
    Button(text="submit", command=get_info10).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==11):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    letter8 = StringVar(value="Choose a Letter")
    importance8= IntVar(value=1)
    OptionMenu(Window_2, letter8, *Alphabet_List).grid(row=9, column=0)
    OptionMenu(Window_2, importance8, *IMPORTANCE_LIST).grid(row=9, column=1)
    letter9 = StringVar(value="Choose a Letter")
    importance9= IntVar(value=1)
    OptionMenu(Window_2, letter9, *Alphabet_List).grid(row=10, column=0)
    OptionMenu(Window_2, importance9, *IMPORTANCE_LIST).grid(row=10, column=1)
    letter10 = StringVar(value="Choose a Letter")
    importance10= IntVar(value=1)
    OptionMenu(Window_2, letter10, *Alphabet_List).grid(row=11, column=0)
    OptionMenu(Window_2, importance10, *IMPORTANCE_LIST).grid(row=11, column=1)
    letter11 = StringVar(value="Choose a Letter")
    importance11= IntVar(value=1)
    OptionMenu(Window_2, letter11, *Alphabet_List).grid(row=12, column=0)
    OptionMenu(Window_2, importance11, *IMPORTANCE_LIST).grid(row=12, column=1)
    Button(text="submit", command=get_info11).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==12):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    letter8 = StringVar(value="Choose a Letter")
    importance8= IntVar(value=1)
    OptionMenu(Window_2, letter8, *Alphabet_List).grid(row=9, column=0)
    OptionMenu(Window_2, importance8, *IMPORTANCE_LIST).grid(row=9, column=1)
    letter9 = StringVar(value="Choose a Letter")
    importance9= IntVar(value=1)
    OptionMenu(Window_2, letter9, *Alphabet_List).grid(row=10, column=0)
    OptionMenu(Window_2, importance9, *IMPORTANCE_LIST).grid(row=10, column=1)
    letter10 = StringVar(value="Choose a Letter")
    importance10= IntVar(value=1)
    OptionMenu(Window_2, letter10, *Alphabet_List).grid(row=11, column=0)
    OptionMenu(Window_2, importance10, *IMPORTANCE_LIST).grid(row=11, column=1)
    letter11 = StringVar(value="Choose a Letter")
    importance11= IntVar(value=1)
    OptionMenu(Window_2, letter11, *Alphabet_List).grid(row=12, column=0)
    OptionMenu(Window_2, importance11, *IMPORTANCE_LIST).grid(row=12, column=1)
    letter12 = StringVar(value="Choose a Letter")
    importance12= IntVar(value=1)
    OptionMenu(Window_2, letter12, *Alphabet_List).grid(row=13, column=0)
    OptionMenu(Window_2, importance12, *IMPORTANCE_LIST).grid(row=13, column=1) 
    Button(text="submit", command=get_info12).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==13):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    letter8 = StringVar(value="Choose a Letter")
    importance8= IntVar(value=1)
    OptionMenu(Window_2, letter8, *Alphabet_List).grid(row=9, column=0)
    OptionMenu(Window_2, importance8, *IMPORTANCE_LIST).grid(row=9, column=1)
    letter9 = StringVar(value="Choose a Letter")
    importance9= IntVar(value=1)
    OptionMenu(Window_2, letter9, *Alphabet_List).grid(row=10, column=0)
    OptionMenu(Window_2, importance9, *IMPORTANCE_LIST).grid(row=10, column=1)
    letter10 = StringVar(value="Choose a Letter")
    importance10= IntVar(value=1)
    OptionMenu(Window_2, letter10, *Alphabet_List).grid(row=11, column=0)
    OptionMenu(Window_2, importance10, *IMPORTANCE_LIST).grid(row=11, column=1)
    letter11 = StringVar(value="Choose a Letter")
    importance11= IntVar(value=1)
    OptionMenu(Window_2, letter11, *Alphabet_List).grid(row=12, column=0)
    OptionMenu(Window_2, importance11, *IMPORTANCE_LIST).grid(row=12, column=1)
    letter12 = StringVar(value="Choose a Letter")
    importance12= IntVar(value=1)
    OptionMenu(Window_2, letter12, *Alphabet_List).grid(row=13, column=0)
    OptionMenu(Window_2, importance12, *IMPORTANCE_LIST).grid(row=13, column=1)
    letter13 = StringVar(value="Choose a Letter")
    importance13= IntVar(value=1)
    OptionMenu(Window_2, letter13, *Alphabet_List).grid(row=14, column=0)
    OptionMenu(Window_2, importance13, *IMPORTANCE_LIST).grid(row=14, column=1)    
    Button(text="submit", command=get_info13).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==14):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    letter8 = StringVar(value="Choose a Letter")
    importance8= IntVar(value=1)
    OptionMenu(Window_2, letter8, *Alphabet_List).grid(row=9, column=0)
    OptionMenu(Window_2, importance8, *IMPORTANCE_LIST).grid(row=9, column=1)
    letter9 = StringVar(value="Choose a Letter")
    importance9= IntVar(value=1)
    OptionMenu(Window_2, letter9, *Alphabet_List).grid(row=10, column=0)
    OptionMenu(Window_2, importance9, *IMPORTANCE_LIST).grid(row=10, column=1)
    letter10 = StringVar(value="Choose a Letter")
    importance10= IntVar(value=1)
    OptionMenu(Window_2, letter10, *Alphabet_List).grid(row=11, column=0)
    OptionMenu(Window_2, importance10, *IMPORTANCE_LIST).grid(row=11, column=1)
    letter11 = StringVar(value="Choose a Letter")
    importance11= IntVar(value=1)
    OptionMenu(Window_2, letter11, *Alphabet_List).grid(row=12, column=0)
    OptionMenu(Window_2, importance11, *IMPORTANCE_LIST).grid(row=12, column=1)
    letter12 = StringVar(value="Choose a Letter")
    importance12= IntVar(value=1)
    OptionMenu(Window_2, letter12, *Alphabet_List).grid(row=13, column=0)
    OptionMenu(Window_2, importance12, *IMPORTANCE_LIST).grid(row=13, column=1)
    letter13 = StringVar(value="Choose a Letter")
    importance13= IntVar(value=1)
    OptionMenu(Window_2, letter13, *Alphabet_List).grid(row=14, column=0)
    OptionMenu(Window_2, importance13, *IMPORTANCE_LIST).grid(row=14, column=1)
    letter14 = StringVar(value="Choose a Letter")
    importance14= IntVar(value=1)
    OptionMenu(Window_2, letter14, *Alphabet_List).grid(row=15, column=0)
    OptionMenu(Window_2, importance14, *IMPORTANCE_LIST).grid(row=15, column=1)
    Button(text="submit", command=get_info14).grid(row=int(no_of_let)+3, column=1)
if (no_of_let==15):
    letter1 = StringVar(value="Choose a Letter")
    importance1= IntVar(value=1)
    OptionMenu(Window_2, letter1, *Alphabet_List).grid(row=2, column=0)
    OptionMenu(Window_2, importance1, *IMPORTANCE_LIST).grid(row=2, column=1)
    letter2 = StringVar(value="Choose a Letter")
    importance2= IntVar(value=1)
    OptionMenu(Window_2, letter2, *Alphabet_List).grid(row=3, column=0)
    OptionMenu(Window_2, importance2, *IMPORTANCE_LIST).grid(row=3, column=1)
    letter3 = StringVar(value="Choose a Letter")
    importance3= IntVar(value=1)
    OptionMenu(Window_2, letter3, *Alphabet_List).grid(row=4, column=0)
    OptionMenu(Window_2, importance3, *IMPORTANCE_LIST).grid(row=4, column=1)
    letter4 = StringVar(value="Choose a Letter")
    importance4= IntVar(value=1)
    OptionMenu(Window_2, letter4, *Alphabet_List).grid(row=5, column=0)
    OptionMenu(Window_2, importance4, *IMPORTANCE_LIST).grid(row=5, column=1)
    letter5 = StringVar(value="Choose a Letter")
    importance5= IntVar(value=1)
    OptionMenu(Window_2, letter5, *Alphabet_List).grid(row=6, column=0)
    OptionMenu(Window_2, importance5, *IMPORTANCE_LIST).grid(row=6, column=1)
    letter6 = StringVar(value="Choose a Letter")
    importance6= IntVar(value=1)
    OptionMenu(Window_2, letter6, *Alphabet_List).grid(row=7, column=0)
    OptionMenu(Window_2, importance6, *IMPORTANCE_LIST).grid(row=7, column=1)
    letter7 = StringVar(value="Choose a Letter")
    importance7= IntVar(value=1)
    OptionMenu(Window_2, letter7, *Alphabet_List).grid(row=8, column=0)
    OptionMenu(Window_2, importance7, *IMPORTANCE_LIST).grid(row=8, column=1)
    letter8 = StringVar(value="Choose a Letter")
    importance8= IntVar(value=1)
    OptionMenu(Window_2, letter8, *Alphabet_List).grid(row=9, column=0)
    OptionMenu(Window_2, importance8, *IMPORTANCE_LIST).grid(row=9, column=1)
    letter9 = StringVar(value="Choose a Letter")
    importance9= IntVar(value=1)
    OptionMenu(Window_2, letter9, *Alphabet_List).grid(row=10, column=0)
    OptionMenu(Window_2, importance9, *IMPORTANCE_LIST).grid(row=10, column=1)
    letter10 = StringVar(value="Choose a Letter")
    importance10= IntVar(value=1)
    OptionMenu(Window_2, letter10, *Alphabet_List).grid(row=11, column=0)
    OptionMenu(Window_2, importance10, *IMPORTANCE_LIST).grid(row=11, column=1)
    letter11 = StringVar(value="Choose a Letter")
    importance11= IntVar(value=1)
    OptionMenu(Window_2, letter11, *Alphabet_List).grid(row=12, column=0)
    OptionMenu(Window_2, importance11, *IMPORTANCE_LIST).grid(row=12, column=1)
    letter12 = StringVar(value="Choose a Letter")
    importance12= IntVar(value=1)
    OptionMenu(Window_2, letter12, *Alphabet_List).grid(row=13, column=0)
    OptionMenu(Window_2, importance12, *IMPORTANCE_LIST).grid(row=13, column=1)
    letter13 = StringVar(value="Choose a Letter")
    importance13= IntVar(value=1)
    OptionMenu(Window_2, letter13, *Alphabet_List).grid(row=14, column=0)
    OptionMenu(Window_2, importance13, *IMPORTANCE_LIST).grid(row=14, column=1)
    letter14 = StringVar(value="Choose a Letter")
    importance14= IntVar(value=1)
    OptionMenu(Window_2, letter14, *Alphabet_List).grid(row=15, column=0)
    OptionMenu(Window_2, importance14, *IMPORTANCE_LIST).grid(row=15, column=1)
    letter15 = StringVar(value="Choose a Letter")
    importance15= IntVar(value=1)
    OptionMenu(Window_2, letter15, *Alphabet_List).grid(row=16, column=0)
    OptionMenu(Window_2, importance15, *IMPORTANCE_LIST).grid(row=16, column=1)
    Button(text="submit", command=get_info15).grid(row=int(no_of_let)+3, column=1)
Window_2.mainloop()
print(myletters)




